controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_api:
    resource: ../../src/Api/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
